# Generated by Django 4.1.4 on 2023-04-05 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Elektron poçt adresi"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "phone_number",
                    models.JSONField(max_length=13, verbose_name="Mobil nömrə"),
                ),
            ],
            options={
                "db_table": "admins",
            },
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_count",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Otaq sayı"
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sahə, m² ilə göstərilmişdir",
                        max_digits=10,
                        null=True,
                        verbose_name="Sahə",
                    ),
                ),
                (
                    "area_of_land",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Torpaq sahəsi, sot ilə göstərilmişdir",
                        max_digits=10,
                        null=True,
                        verbose_name="Torpaq sahəsi",
                    ),
                ),
                (
                    "coast",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Qiymət, manat ilə göstərilmişdir",
                        max_digits=10,
                        null=True,
                        verbose_name="Qiymət",
                    ),
                ),
                (
                    "location_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Koordinatı daxil edin",
                        max_digits=10,
                        null=True,
                        verbose_name="Coğrafi enlik",
                    ),
                ),
                (
                    "location_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Koordinatı daxil edin",
                        max_digits=10,
                        null=True,
                        verbose_name="Coğrafi uzunluq",
                    ),
                ),
                (
                    "type",
                    models.BigIntegerField(
                        choices=[
                            (1, "Kirayə"),
                            (2, "Günlük kirayə"),
                            (3, "Satış"),
                            (4, "Başqa"),
                        ],
                        verbose_name="Tip",
                    ),
                ),
                (
                    "sub_type",
                    models.BigIntegerField(
                        choices=[
                            (1, "sub_flat old constructed"),
                            (2, "sub_flat new constructed"),
                            (3, "sub_home / villa"),
                            (4, "sub_garden"),
                            (5, "sub_office"),
                            (6, "sub_garage"),
                            (7, "sub_object building"),
                            (8, "sub_land"),
                            (9, "sub_another"),
                        ],
                        verbose_name="Alt tip",
                    ),
                ),
                (
                    "have_government_deed",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Order varsa 'True', yoxdursa 'False' seçin",
                        null=True,
                        verbose_name="Order",
                    ),
                ),
                (
                    "have_mortgage_support",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Ipoteka dəstəyi varsa 'True', yoxdursa 'False' seçin",
                        null=True,
                        verbose_name="Ipoteka dəstəyi",
                    ),
                ),
                (
                    "building_stage_height",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Bina mərtəbə sayı"
                    ),
                ),
                (
                    "stage",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Mərtəbə"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ətraflı məlumat"
                    ),
                ),
                ("view_count", models.BigIntegerField(verbose_name="Baxış sayı")),
                (
                    "advertisement_create_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "advertisement_expire_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "advertisement_deleted_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("city_id", models.BigIntegerField(verbose_name="Şəhər")),
                (
                    "region_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="Rayon"),
                ),
                ("town_ship_id", models.BigIntegerField(verbose_name="Qəsəbə")),
                (
                    "metro_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="Metro"),
                ),
                (
                    "target_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Target"
                    ),
                ),
                ("repair", models.BooleanField(default=False, verbose_name="Təmir")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Ünvan"),
                ),
                (
                    "building_type",
                    models.BigIntegerField(
                        choices=[
                            (1, "Köhnə tikili"),
                            (2, "Yeni tikili"),
                            (3, "Ev / villa"),
                            (4, "Bağ"),
                            (5, "Ofis"),
                            (6, "Qaraj"),
                            (7, "Obyekt"),
                            (8, "Torpaq"),
                            (9, "Başqa"),
                        ],
                        verbose_name="Bina Tikili tipi",
                    ),
                ),
                (
                    "admin_confirmation_status",
                    models.BigIntegerField(
                        blank=True,
                        choices=[
                            (1, "Gözləmədədir"),
                            (2, "Təsdiqlənib"),
                            (3, "Vaxtı bitmişdir"),
                            (4, "Başqa"),
                        ],
                        null=True,
                        verbose_name="Elan_təsdiqlənmə statusu",
                    ),
                ),
                (
                    "advertisement_type",
                    models.BigIntegerField(
                        choices=[
                            (1, "Normal"),
                            (2, "Önə çəkilmiş"),
                            (3, "Vip"),
                            (4, "Premium"),
                            (5, "Başqa"),
                        ],
                        verbose_name="Elan tipi",
                    ),
                ),
                (
                    "advertisement_type_expire_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "building_project_type",
                    models.BigIntegerField(
                        choices=[(1, "Xruşovka"), (2, "Stalinka"), (3, "Başqa")],
                        verbose_name="Mənzil layihə tipi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elan",
                "verbose_name_plural": "Elanlar",
                "db_table": "advertisements",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Şəhər"
                    ),
                ),
            ],
            options={
                "verbose_name": "Şəhər",
                "verbose_name_plural": "Şəhərlər",
                "db_table": "cities",
            },
        ),
        migrations.CreateModel(
            name="Metro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Metro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Metro",
                "verbose_name_plural": "Metrolar",
                "db_table": "metros",
            },
        ),
        migrations.CreateModel(
            name="NormalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Elektron poçt adresi"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Şirkət adı"
                    ),
                ),
                (
                    "person_in_charge",
                    models.CharField(max_length=255, verbose_name="Əlaqədər şəxs"),
                ),
                (
                    "phone_number",
                    models.JSONField(max_length=13, verbose_name="Mobil nömrə"),
                ),
                (
                    "user_type",
                    models.BigIntegerField(
                        choices=[
                            (1, "normal_seller"),
                            (2, "rieltor"),
                            (3, "agency"),
                            (4, "fake_user"),
                            (5, "another"),
                        ],
                        default=4,
                        verbose_name="Istifadəçi tipi",
                    ),
                ),
                ("role", models.TextField(blank=True, null=True, verbose_name="role")),
            ],
            options={
                "verbose_name": "İstifadəçi",
                "verbose_name_plural": "İstifadəçilər",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.BigIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending Payment"),
                            (2, "Transfer Success"),
                            (3, "Transfer Failed"),
                        ],
                        null=True,
                    ),
                ),
                ("order", models.CharField(blank=True, max_length=255, null=True)),
                ("session", models.CharField(blank=True, max_length=255, null=True)),
                ("user_id", models.BigIntegerField()),
            ],
            options={
                "verbose_name": "Ödəniş",
                "verbose_name_plural": "Ödənişlər",
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Rayon"
                    ),
                ),
                ("city_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Rayon",
                "verbose_name_plural": "Rayonlar",
                "db_table": "regions",
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nişangah"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nişangah",
                "verbose_name_plural": "Nişangahlar",
                "db_table": "targets",
            },
        ),
        migrations.CreateModel(
            name="Township",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Qəsəbə"
                    ),
                ),
                ("region_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Qəsəbə",
                "verbose_name_plural": "Qəsəbələr",
                "db_table": "townships",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "end_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "operation",
                    models.PositiveIntegerField(
                        blank=True, choices=[(1, "Debet"), (2, "Credit")], null=True
                    ),
                ),
                ("order", models.CharField(blank=True, max_length=255, null=True)),
                ("session", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="evial_app.normaluser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tranzaksiya",
                "verbose_name_plural": "Tranzaksiyalar",
                "db_table": "transactions",
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("deleted_date", models.DateTimeField(verbose_name="Silinmə tarixi")),
                (
                    "advertisement",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="evial_app.advertisement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Şəkil",
                "verbose_name_plural": "Şəkillər",
                "db_table": "pictures",
            },
        ),
        migrations.CreateModel(
            name="CustomUserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custom_user_permissions",
            },
        ),
        migrations.CreateModel(
            name="CustomUserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custom_user_groups",
            },
        ),
        migrations.AddField(
            model_name="advertisement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="evial_app.normaluser",
                to_field="email",
                verbose_name="İstifadəçi",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True, through="evial_app.CustomUserGroup", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                through="evial_app.CustomUserPermission",
                to="auth.permission",
            ),
        ),
    ]
