# Generated by Django 4.1.4 on 2023-04-01 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Elektron poçt adresi"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Şirkət adı"
                    ),
                ),
                (
                    "person_in_charge",
                    models.CharField(max_length=255, verbose_name="person_in_charge"),
                ),
                (
                    "phone_number",
                    models.JSONField(
                        max_length=255, unique=True, verbose_name="Mobil nömrə"
                    ),
                ),
                (
                    "user_type",
                    models.BigIntegerField(
                        choices=[
                            (1, "normal_seller"),
                            (2, "rieltor"),
                            (3, "agency"),
                            (4, "fake_user"),
                            (5, "another"),
                            (0, "##BUG##"),
                        ],
                        default=4,
                        verbose_name="Istifadəçi tipi",
                    ),
                ),
                ("role", models.TextField(blank=True, null=True, verbose_name="role")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_count",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Otaq sayı"
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sahə, m² ilə göstərilmişdir",
                        max_digits=10,
                        null=True,
                        verbose_name="Sahə",
                    ),
                ),
                (
                    "area_of_land",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Torpaq sahəsi, sot ilə göstərilmişdir",
                        max_digits=10,
                        null=True,
                        verbose_name="Torpaq sahəsi",
                    ),
                ),
                (
                    "coast",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Torpaq sahəsi, sot ilə göstərilmişdir",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "location_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Koordinatı daxil edin",
                        max_digits=10,
                        null=True,
                        verbose_name="Coğrafi enlik",
                    ),
                ),
                (
                    "location_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Koordinatı daxil edin",
                        max_digits=10,
                        null=True,
                        verbose_name="Coğrafi uzunluq",
                    ),
                ),
                (
                    "type",
                    models.BigIntegerField(
                        choices=[
                            (1, "Kirayə"),
                            (2, "Günlük kirayə"),
                            (3, "Satış"),
                            (4, "Başqa"),
                        ],
                        verbose_name="Tip",
                    ),
                ),
                (
                    "have_government_deed",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Order varsa 'True', yoxdursa 'False' seçin",
                        null=True,
                        verbose_name="Order",
                    ),
                ),
                (
                    "have_mortgage_support",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Ipoteka dəstəyi varsa 'True', yoxdursa 'False' seçin",
                        null=True,
                        verbose_name="Ipoteka dəstəyi",
                    ),
                ),
                (
                    "building_stage_height",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Bina mərtəbə sayı"
                    ),
                ),
                (
                    "stage",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Mərtəbə"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ətraflı məlumat"
                    ),
                ),
                ("view_count", models.BigIntegerField(verbose_name="Baxış sayı")),
                (
                    "advertisement_create_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "advertisement_expire_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "advertisement_deleted_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("repair", models.BooleanField(default=False, verbose_name="Təmir")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Ünvan"),
                ),
                (
                    "building_type",
                    models.BigIntegerField(
                        blank=True,
                        choices=[
                            (1, "Köhnə tikili"),
                            (2, "Yeni tikili"),
                            (3, "Ev / villa"),
                            (4, "Bağ"),
                            (5, "Ofis"),
                            (6, "Qaraj"),
                            (7, "Obyekt"),
                            (8, "Torpaq"),
                            (9, "Başqa"),
                        ],
                        null=True,
                        verbose_name="Bina Tikili tipi",
                    ),
                ),
                (
                    "admin_confirmation_status",
                    models.BigIntegerField(
                        blank=True,
                        choices=[
                            (1, "Gözləmədədir"),
                            (2, "Təsdiqlənib"),
                            (3, "Vaxtı bitmişdir"),
                            (4, "Başqa"),
                        ],
                        null=True,
                        verbose_name="Elan_təsdiqlənmə statusu",
                    ),
                ),
                (
                    "advertisement_type",
                    models.BigIntegerField(
                        blank=True,
                        choices=[
                            (1, "Normal"),
                            (2, "Önə çəkilmiş"),
                            (3, "Vip"),
                            (4, "Premium"),
                            (5, "Başqa"),
                        ],
                        null=True,
                        verbose_name="Elan tipi",
                    ),
                ),
                (
                    "advertisement_type_expire_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "building_project_type",
                    models.BigIntegerField(
                        choices=[(1, "Xruşovka"), (2, "Stalinka"), (3, "Başqa")],
                        default=3,
                        verbose_name="Mənzil layihə tipi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elan",
                "verbose_name_plural": "Elanlar",
                "db_table": "advertisements",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Şəhər")),
            ],
            options={
                "verbose_name": "Şəhər",
                "verbose_name_plural": "Şəhərlər",
                "db_table": "cities",
            },
        ),
        migrations.CreateModel(
            name="Metro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Metro")),
            ],
            options={
                "verbose_name": "Metro",
                "verbose_name_plural": "Metrolar",
                "db_table": "metros",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Rayon")),
                (
                    "city_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rayon",
                "verbose_name_plural": "Rayonlar",
                "db_table": "regions",
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "targets",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("end_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "operation",
                    models.PositiveIntegerField(choices=[(1, "Debet"), (2, "Credit")]),
                ),
                ("order_id", models.CharField(max_length=255)),
                ("session_id", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tranzaksiya",
                "verbose_name_plural": "Tranzaksiyalar",
                "db_table": "transactions",
            },
        ),
        migrations.CreateModel(
            name="Township",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Qəsəbə")),
                (
                    "region_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qəsəbə",
                "verbose_name_plural": "Qəsəbələr",
                "db_table": "townships",
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("deleted_date", models.DateTimeField(verbose_name="Silinmə tarixi")),
                (
                    "advertisement_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.advertisement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Şəkil",
                "verbose_name_plural": "Şəkillər",
                "db_table": "pictures",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.BigIntegerField(
                        choices=[
                            (1, "Pending Payment"),
                            (2, "Transfer Success"),
                            (3, "Transfer Failed"),
                        ]
                    ),
                ),
                ("order_id", models.CharField(max_length=255)),
                ("session_id", models.CharField(max_length=255)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödəniş",
                "verbose_name_plural": "Ödənişlər",
                "db_table": "payments",
            },
        ),
        migrations.AddField(
            model_name="advertisement",
            name="city_id",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.city",
                verbose_name="Şəhər",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="metro_id",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.metro",
                verbose_name="Metro",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="region_id",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.region",
                verbose_name="Rayon",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="target_id",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.target",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="town_ship_id",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.township",
                verbose_name="Qəsəbə",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="İstifadəçi",
            ),
        ),
    ]
