# Generated by Django 4.1.4 on 2023-03-31 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="advertisement",
            table="advertisements",
        ),
        migrations.AlterModelTable(
            name="city",
            table="cities",
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="users",
        ),
        migrations.AlterModelTable(
            name="metro",
            table="metros",
        ),
        migrations.AlterModelTable(
            name="payment",
            table="payments",
        ),
        migrations.AlterModelTable(
            name="picture",
            table="pictures",
        ),
        migrations.AlterModelTable(
            name="region",
            table="regions",
        ),
        migrations.AlterModelTable(
            name="target",
            table="targets",
        ),
        migrations.AlterModelTable(
            name="township",
            table="townships",
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="transactions",
        ),
    ]
